### ISSUE TITLE
Does Not Respect Quoted Strings

### ISSUE THREAD

**Issue by joeblau** [naoty/SwiftCSV#32]
If you have a CSV like this

```
first,second
"abc","de,f"
```

This gets parsed to
rows[0]["first"] = "abc"
rows[0]["second"] = "de"

and ",f" is left off when it should be included in `second`

**Comment by JavaNut13** [comment]
[I've been working on this in my fork](https://github.com/JavaNut13/SwiftCSV)

**Comment by naoty** [comment]
@JavaNut13 Your fork is great! Would you send a pull request?

**Comment by joeblau** [comment]
I just realized that the project is deprecated; I'm going to use another solution.

**Comment by naoty** [comment]
@joeblau I'm sorry :bow: If you are finding another library, I'll recommend [this one](https://github.com/Daniel1of1/CSwiftV). Because some people said to me that they want to help, I just dropped the plan to make deprecated this library.

**Comment by naoty** [comment]
@joeblau I merged @JavaNut13's pull request and released as `0.3.1`. Please check it.
