### ISSUE TITLE
Fails on newlines

### ISSUE THREAD

**Issue by p2** [naoty/SwiftCSV#4]
Parsing fails when the CSV file contains newline data, such as:

```csv
h1,h2,h3
"a","here
are
newlines","c"
```

You cannot use `componentsSeparatedByCharactersInSet` in a CSV parser, you will need to use `NSScanner`.

**Comment by mathieu166** [comment]
getaaron, how did you work around that problem?

**Comment by getaaron** [comment]
@mathieu166 I stopped using this library and used one based on `NSScanner` instead
