### ISSUE TITLE
What does [DEPRECATED] mean?

### ISSUE THREAD

**Issue by nkanellopoulos** [naoty/SwiftCSV#46]
Hi!
Does this mean you have decided not to maintain this library any more?

**Comment by naoty** [comment]
Yes. I don't have enough time to maintain this library. So, if anyone wants to maintain this, I will welcome him/her as a collaborator.

**Comment by grantkemp** [comment]
Hi - It would be a pity to deprecate this. I see there are other libraries that do Swift - but this looks the most popular.  
 I am happy to help with testing it out i see people have contributed Swift 3 fixes already.

**Comment by naoty** [comment]
@grantkemp Thank you! Can I make you a collaborator?

**Comment by grantkemp** [comment]
Sure - feel free.  I don't know the library well enough yet -barring using it but I can merge and do my best to keep it updated as I use it on one of my apps.

**Comment by naoty** [comment]
@grantkemp Thank you so much! I added you as a collaborator!

**Comment by naoty** [comment]
Since I found a collaborator, I will remove `[DEPRECATED]`. 👍
