### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by jstart** [naoty/SwiftCSV#5]
Any chance for Cocoapods support?  I am not sure if Swift libraries are fully supported in Cocoapods, but I'd be happy to provide a Pull Request with podspec.

**Comment by jeeftor** [comment]
Swift is supported by cocoa pods current beta right now FYI... Maybe i'll try to fork a branch if i ever have time and set it up

**Comment by naoty** [comment]
@jeeftor Thanks! I'll try to support cocoapods 0.36.0.beta2.

**Comment by naoty** [comment]
@jstart @jeeftor I has supported CocoaPods 0.36.0.beta.2!

**Comment by jstart** [comment]
@naoty Awesome thanks!
