### ISSUE TITLE
Review Swift 3 and release? 

### ISSUE THREAD

**Issue by grantkemp** [naoty/SwiftCSV#53]
Hi @naoty  
I just ran through the tests and it looks like its ok. 
Do you want to have a go? and if you are happy we can release to live?

**Comment by naoty** [comment]
Hi! I will review develop branch today or tomorrow.

**Comment by grantkemp** [comment]
Thanks!

**Comment by grantkemp** [comment]
@naoty  happy to merge master?

**Comment by naoty** [comment]
@grantkemp Yes! Sorry for late reply!

**Comment by grantkemp** [comment]
I am just going to do this! Lets realease. 

Cheers
