### ISSUE TITLE
Do you plan on supporting swift 5? *insert Guess you'll try then? meme*

### ISSUE THREAD

**Issue by soryncrash13** [naoty/SwiftCSV#65]
Do you plan on supporting swift 5? *insert Guess you'll try then? meme*
I just want to please let me and everyone know if this is still a work in progress or has it reached its final destination point? Thanks 😸

**Comment by DivineDominion** [comment]
A fork currently supports Swift 5: https://github.com/phpmaple/SwiftCSV/tree/master

**Comment by soryncrash13** [comment]
Thank you so much. This ticket can be closed as solved. Take care
