### ISSUE TITLE
Optionnal type NSURL

### ISSUE THREAD

**Issue by mathlarocque** [naoty/SwiftCSV#8]
Hi, When I tried to implement your example, I got an error saying 
Value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?

If I add '!' I must also add it to csv!.colums['my_column_name'] then I got csv doesn't have a member colums.

If I use ? I got NSURL not unwrapped did you mean '!' or '?'

I'm using xcode 6.1.1 and cocoapods 0.36.0.beta.2

Here is my code : 

        let csvURL = NSURL(string: "test.csv")
        var error: NSErrorPointer = nil
        let csv = CSV(contentsOfURL: csvURL, error: error)        
        let testValues = csv.colums["name_test"]

I suggest that you update your example to match what should be done. 
I'm a little new to swift.

**Comment by naoty** [comment]
@mathlarocque You should use optional binding, `if let csvURL = NSURL(string: "test.csv")`. I will modify the sample code soon.

**Comment by naoty** [comment]
@mathlarocque I have modified the sample codes by ac1559971068595e6d0e161dcd0e81abffabc816.
