### ISSUE TITLE
Convert empty strings to nil

### ISSUE THREAD

**Issue by dbettermann** [naoty/SwiftCSV#9]
Hello,

Can we add a property to the parser that converts empty strings to nil? Currently if I want to set a value as nil instead of "" I have to do:

```swift
(row["Key"] as String!).isEmpty ? nil : row["Key"]
```

which is fine for a few values, but it gets a little clunky if you have more than a few.

**Comment by naoty** [comment]
@dbettermann Thank you for the proposal. An application, not the parser, should be responsible for the convert. The parser always returns all values in a CSV file as `String` type.

**Comment by dbettermann** [comment]
That makes sense. In this case it would be nice if the `Dictionary` subscript returned `Value` instead of `Value?`.
